server:
  port: 8080
spring:
  application:
    name: micro-service
  datasource:
    url: jdbc:mysql://localhost:3306/employee_directory?useSSL=false&serverTimezone=UTC
    username: employee
    password: employEE!@#123
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:18080
      eager: true
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
url:
  name: tyun
  address: www.tyun.cn
management:
  endpoints:
    web:
      exposure:
        include: '*'